import NextHead from "next/head";

export default function Head() {
  return (
    <>
      <title>Ye Yint Thway</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" type="image/x-icon" href="/boy.ico" />
    </>
  );
}
